# Project-wide Gradle settings.
android.defaults.buildfeatures.compose=true

# Mémoire réduite pour éviter le daemon crash
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false

# Kotlin
kotlin.code.style=official
kotlin.incremental=false
kotlin.daemon.jvm.options=-Xmx1024m

# Kapt
kapt.use.worker.api=false
kapt.incremental.apt=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true